#!/bin/sh
# C compiler wrapper for CMake: Zig's clang targeting $ZIG_TARGET. $ZIG is the zig command (default: python3 -m ziglang).
exec ${ZIG:-python3 -m ziglang} cc -target ${ZIG_TARGET:-x86_64-windows-gnu} "$@"
