/* Description of a recompiled DLL (script module), shared by the generated per-module data (host/gen_moddata.py)
   and the Windows host. */
#ifndef RECOMP_MOD_H
#define RECOMP_MOD_H
#include <stdint.h>
#include "rt.h"

typedef struct { uint32_t va; guest_fn fn; } rc_ent;

typedef struct {
    const char *name;               /* file name the engine loads, e.g. "allobjs.osm" (compared case-insensitively) */
    uint32_t base, size, entry;     /* where the recompiled code expects the image, its size, its DllMain */
    uint32_t file_base;             /* ImageBase in the file (differs from base when the module was lifted rebased) */
    uint32_t crc;                   /* crc32 of the code ranges as mapped at `base` */
    int manual;                     /* 0: Windows maps the file at its preferred base; 1: the host maps and relocates it */
    unsigned ncode;
    const uint32_t *code_lo, *code_hi;
    const rc_ent *table;            /* recompiled functions, sorted by address */
    const unsigned *table_n;
    guest_fn (*lookup)(uint32_t va);
} RecompModDesc;

extern const RecompModDesc *const recomp_mods[];   /* null-terminated; generated by the build (out/mods.c) */
#endif
