#!/usr/bin/env python3
"""gen_hostdata.py <meta.json> <exe> <out.c>: tables the Windows host needs (imports, IAT slots, SMC fields, exe identity)."""
import sys, json, zlib
meta = json.load(open(sys.argv[1])); exe = open(sys.argv[2], 'rb').read()
def cstr(s):
    return '"' + ''.join(('\\%03o' % ord(ch)) if ch in '?"\\' or ord(ch) < 32 or ord(ch) > 126 else ch for ch in s) + '"'
imps = meta['imports']
slot = {}
for k, v in meta['iat'].items(): slot.setdefault(int(v), int(k, 16))
assert sorted(slot) == list(range(len(imps))), 'IAT slots do not cover every import'
out = ['/* generated by gen_hostdata.py */', '#include <stdint.h>',
       'typedef struct { const char *dll, *name; } ImpDef;', 'const ImpDef hd_imports[] = {']
out += [f'    {{{cstr(d)}, {cstr(n)}}},' for d, n in imps]
out += ['};', f'const unsigned hd_nimports = {len(imps)};',
        'const uint32_t hd_iat_slot[] = {' + ','.join(f'0x{slot[i]:x}u' for i in range(len(imps))) + '};']
flds = []
for va, fields in meta['smc_sites'].items():
    for f in fields:
        a = int(va, 16) + f['off']; flds.append((a, a + f['size']))
flds.sort()
out += [f'const unsigned hd_nsmc = {len(flds)};',
        'const uint32_t hd_smc_lo[] = {' + ','.join(f'0x{a:x}u' for a, b in flds) + '};',
        'const uint32_t hd_smc_hi[] = {' + ','.join(f'0x{b:x}u' for a, b in flds) + '};',
        f'const uint32_t hd_entry = 0x{meta["entry"]:x}u;', f'const uint32_t hd_base = 0x{meta["base"]:x}u;',
        f'const uint32_t hd_exe_size = {len(exe)}u;', f'const uint32_t hd_exe_crc = 0x{zlib.crc32(exe) & 0xFFFFFFFF:08x}u;']
secs = [(a, a + n) for (nm, a, n, ch) in meta['sections'] if ch & 0x20000000]
out += [f'const unsigned hd_ncode = {len(secs)};',
        'const uint32_t hd_code_lo[] = {' + ','.join(f'0x{a:x}u' for a, b in secs) + '};',
        'const uint32_t hd_code_hi[] = {' + ','.join(f'0x{b:x}u' for a, b in secs) + '};']
open(sys.argv[3], 'w').write('\n'.join(out) + '\n')
print(f'{len(imps)} imports, {len(flds)} SMC fields, crc {zlib.crc32(exe) & 0xFFFFFFFF:08x}')
