#!/usr/bin/env python3
"""gen_ifaces.py [mingw include dir] > port/dx/ifaces.h

Writes the COM interface layouts the DirectX front ends implement (method order and argument counts) from MinGW's
d3d9.h / dsound.h / dinput.h / ddraw.h, which ship with Zig (`pip install ziglang`). The generated header is committed;
tools/check_com.py verifies it, so nobody has to type a vtable by hand again."""
import os, re, sys
IFACES = ["IDirect3D9", "IDirect3DDevice9", "IDirect3DTexture9", "IDirect3DCubeTexture9", "IDirect3DVolumeTexture9", "IDirect3DSurface9", "IDirect3DVolume9",
          "IDirect3DVertexBuffer9", "IDirect3DIndexBuffer9", "IDirect3DSwapChain9", "IDirect3DQuery9", "IDirect3DStateBlock9", "IDirect3DVertexDeclaration9",
          "IDirect3DVertexShader9", "IDirect3DPixelShader9", "IDirectSound", "IDirectSoundBuffer", "IDirectSound3DBuffer", "IDirectSound3DListener",
          "IDirectSoundNotify", "IKsPropertySet", "IDirectInputA", "IDirectInput2A", "IDirectInput7A", "IDirectInputDeviceA", "IDirectInputDevice2A", "IDirectInputDevice7A", "IDirectDraw"]
def inc_dir():
    if len(sys.argv) > 1: return sys.argv[1]
    import ziglang; return os.path.join(os.path.dirname(ziglang.__file__), "lib", "libc", "include", "any-windows-any")
def parse(inc):
    decl = {}
    for h in ("d3d9.h", "dsound.h", "dinput.h", "ddraw.h"):
        src = open(os.path.join(inc, h), errors="replace").read()
        for m in re.finditer(r"DECLARE_INTERFACE_(?:IID_)?\(\s*(\w+)\s*,\s*(\w+)\s*(?:,\s*\"[^\"]*\")?\s*\)\s*\{(.*?)\n\};", src, re.S):
            name, base, body = m.groups(); meths = []
            for mm in re.finditer(r"STDMETHOD_?\((?:[^,()]*,\s*)?(\w+)\)\s*\(\s*THIS(_?)([^;]*?)\)\s*PURE\s*;", body, re.S):
                n, under, rest = mm.groups(); meths.append((n, rest.count(",") + 1 if under else 0))
            decl.setdefault(name, (base, meths))
    return decl
def full(decl, name):
    if name == "IUnknown": return [("QueryInterface", 2), ("AddRef", 0), ("Release", 0)]
    base, meths = decl[name]; inherited = full(decl, base); names = {m[0] for m in inherited}
    return inherited + [m for m in meths if m[0] not in names]
GUIDS = ["IID_" + n for n in IFACES] + ["IID_IDirectSoundBuffer8", "IID_IDirectSound8", "IID_IDirectInputDevice8A", "GUID_SysKeyboard", "GUID_SysMouse",
         "IID_IDirectDraw2", "IID_IDirectDraw4", "IID_IDirectDraw7", "GUID_XAxis", "GUID_YAxis", "GUID_ZAxis", "GUID_Joystick", "IID_IDirectInput8A"]
def guids(inc):
    out = {}
    for h in ("d3d9.h", "dsound.h", "dinput.h", "ddraw.h"):
        src = open(os.path.join(inc, h), errors="replace").read()
        for m in re.finditer(r"DEFINE_GUID\(\s*(\w+)\s*,([^)]*)\)", src):
            v = [int(x.strip().rstrip("uUlL"), 0) for x in m.group(2).split(",")]
            if len(v) == 11: out.setdefault(m.group(1), v)
    return out
def guid_bytes(v):
    b = list(v[0].to_bytes(4, "little")) + list(v[1].to_bytes(2, "little")) + list(v[2].to_bytes(2, "little")) + v[3:]
    return "{ " + ", ".join(f"0x{x:02x}" for x in b) + " }"
if __name__ == "__main__":
    decl = parse(inc_dir()); gd = guids(inc_dir())
    print("/* ifaces.h: COM interface layouts (method order and argument count, not counting `this`), generated by\n"
          " * port/tools/gen_ifaces.py from MinGW's DirectX headers. Do not edit; regenerate. */")
    for n in IFACES:
        if n not in decl: sys.exit(f"{n} not found in the headers")
        print(f'#define IFACE_{n} "' + " ".join(f"{m}:{a}" for m, a in full(decl, n)) + '"')
    print("/* interface and device GUIDs as the 16 bytes they occupy in memory */")
    for g in GUIDS:
        if g in gd: print(f"#define {g} {guid_bytes(gd[g])}")
        else: print(f"/* {g}: not in the headers */")
